$('.owl-carousel').owlCarousel({
    loop:true,
    margin:30,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        360:{
            items:1
        },
        600:{
            items:1
        },
        768:{
            items:2
        },
        792:{
            items:2
        },
        900:{
            items:2
        },
        1000:{
            items:3
        }
    }
})